# -*- coding: utf-8 -*-

ALTO_TAKE_OFF_NUM = 100
ALTO_GO_NUM = 10
ALTO_BREAK_RIGHT_DELAY_NUM = 0
ALTO_BREAK_RIGHT_NUM = 10
ALTO_STOP_TO_TARGET_POLE_NUM = 250
ALTO_DETECT_FIRST_CORNER_NUM = 10
ALTO_STOP_TO_FIRST_CORNER_NUM = 100
ALTO_DETECT_SECOND_CORNER_NUM = 10
ALTO_STOP_TO_SECOND_CORNER_NUM = 100
ALTO_BACK_NUM = 500
ALTO_DETECT_END_POLE_NUM = 5
ALTO_BREAK_LEFT_DELAY_NUM = 5
ALTO_BREAK_LEFT_NUM = 10
ALTO_LAND_NUM = 50